# Generated by Django 4.2.6 on 2023-12-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adv_Register',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
