# Generated by Django 4.2.6 on 2023-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advbook_app', '0002_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
