# Generated by Django 4.2.6 on 2023-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advbook_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
