# Generated by Django 4.2.6 on 2023-11-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advbook_app', '0005_adv_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv_register',
            name='approval',
            field=models.CharField(default='waiting for approval', max_length=50),
        ),
    ]
