# Generated by Django 4.2.6 on 2023-12-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advbook_app', '0006_adv_register_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv_register',
            name='achievement',
            field=models.TextField(default='No achievement'),
        ),
    ]
