# Generated by Django 4.2.6 on 2023-12-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advbook_app', '0009_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField()),
                ('rating', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('advocate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advbook_app.adv_register')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advbook_app.register')),
            ],
        ),
    ]
