# Generated by Django 4.2.6 on 2023-12-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advbook_app', '0010_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
