# Generated by Django 4.2.6 on 2023-12-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advbook_app', '0012_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='advocate_id',
            new_name='advocateid',
        ),
    ]
